### ISSUE TITLE
怎么查询token余额

### ISSUE THREAD

**Issue by jinya43073** [yihau/solana-web3-demo#1]
connection.getBanlance 查询SOL的余额，如果要查询代币（比如USDC）的需要怎么做呢，另外如果一个account有多个USDC的地址可以查到吗，谢谢大佬

**Comment by yihau** [comment]
你好
有新增兩個範例在 src/token/get-all-account-by-owner 和 src/token/get-token-account-balance
應該可以達成你想要的需求

**Comment by jinya43073** [comment]
谢谢大佬，终于搞通，还想问一下关于费用预估的问题，看文档有个feeCalculator的接口，没看到该怎么用它，目的是希望每次转账或者交互前，预估一下余额是否够覆盖交易

**Comment by yihau** [comment]
feeCalculator 這個概念看起來是官方希望能夠動態調整fee的計算方式
目前的fee僅有計算lamportsPerSignature
也就是說你這筆tx裡面有幾個簽名就需要付幾個lamportsPerSignature

**Comment by jinya43073** [comment]
刚尝试了一下，通过最近区块查询到的lamportsPerSignature值是5000，也就是说每次交易需要消耗0.000005sol，这个费用只跟签名个数有关吗，跟交互复杂程度没有关系吗？

**Comment by yihau** [comment]
目前僅有收取簽名數量的費用而已 未來就不清楚了

**Comment by jinya43073** [comment]
谢谢大佬解答

**Comment by jinya43073** [comment]
大佬，又是我，不好意思（cry.jpg）, 给账号增加token地址的时候，报错insufficient lamports 1029989, need 2039280，是因为lamports给得不足吗，是这个await SPLToken.Token.getMinBalanceRentForExemptAccount(conn)不足？
Token/create-token-account/main.ts
    SystemProgram.createAccount({
      fromPubkey: feePayer.publicKey,
      newAccountPubkey: mint.publicKey,
      space: SPLToken.MintLayout.span,
      lamports: await SPLToken.Token.getMinBalanceRentForExemptMint(connection),
      programId: SPLToken.TOKEN_PROGRAM_ID,
    }),

另外第二种方法SPLToken.Token.createAssociatedTokenAccountInstruction调用中传了两个feePayer.publicKey，并没有看到tokenAccount相关

**Comment by jinya43073** [comment]
token/create-token-account/main.ts 这个文件中的两种方法

**Comment by jinya43073** [comment]
1. insufficient lamports 1029989, need 2039280 这个问题解决了，是付费的账号手续费不足
2. 现在问题是，新建立的USDC地址都跑到付手续费的账号下面去了。我尝试更改方法一中的ownerPublic，代码没有通过，如果想建立的USDC不在付费账号上，参数是怎么设置的。

**Comment by yihau** [comment]
更改方法一的owner pubkey是正確的方向

```js
  let alice = Keypair.generate();
  let tokenAccount = Keypair.generate();
  let tx1 = new Transaction();
  tx1.add(
    SystemProgram.createAccount({
      fromPubkey: feePayer.publicKey,
      newAccountPubkey: tokenAccount.publicKey,
      space: SPLToken.AccountLayout.span,
      lamports: await SPLToken.Token.getMinBalanceRentForExemptAccount(
        connection
      ),
      programId: SPLToken.TOKEN_PROGRAM_ID,
    }),
    SPLToken.Token.createInitAccountInstruction(
      SPLToken.TOKEN_PROGRAM_ID,
      mintPubkey,
      tokenAccount.publicKey,
      alice.publicKey // <===== 這裡填入什麼public key 他就是誰的token account
    )
  );
  tx1.feePayer = feePayer.publicKey;
```

在做的時候記得把方法二的相關代碼註解掉

**Comment by jinya43073** [comment]
谢谢大佬提醒，方法一方法二是分开尝试的
1. 更换ownerpublic，有作用了，但地址变成usdc地址，sol地址不见了，查区块，里面就只剩一个usdc地址了，这是正常的吗，用https://www.sollet.io/登录看到账号里原来sol的地址变成了usdc地址，
2.   方法一中SPLToken.Token.createInitMintInstruction的参数设置与src/token/create-mint/main.ts 中的参数设置不同，作用有什么区别吗
3. 方法二67 68 行两个feePayer.publicKey都是必须的吗？方法二中没有地方有传入tokenAccount

**Comment by yihau** [comment]
1. 理論上你應該是先得到sollet裡面的那個SOL地址，然後你可以再把這個地址當成owner傳進去裡面。這樣你就可以產出這個SOL地址所擁有的USDC地址了！
2. 咦！你是在說 src/token/create-token-account的方法一嗎？那邊應該是用了 SystemProgram.createAccount + SPLToken.Token.createInitAccountInstruction 沒有用到create init mint的instruction
3. 喔喔我瞭解了！這邊這樣寫可能會容易誤會，我會補更多說明在那邊。我在這邊也簡單跟你說一下：方法二的token account是計算出來的。assoTokenAccountPubkey 這個就是方法二的token account。同一個mint跟同一個owner來算每次都會得到一樣的結果，所以官方有比較推薦這個方式，這樣大家就不用管一堆account，可以要用的時候再拿自己的account去算一下。58行的那個就是要算assoTokenAccountPubkey的owner。 而67行那邊也是帶owner，要跟剛剛算的時候帶進去的owner是同一個數值。68行的話就是feePayer的部分。

**Comment by yihau** [comment]
code 這邊我有更新一版上去
如果你要看我的第三點的論述的話記得先不要pull最新版
或是你可以直接拉最新版看code裡面寫的也可以！
