### ISSUE TITLE
NFT example not working in HTML

### ISSUE THREAD

**Issue by Ben-v-starloop** [yihau/solana-web3-demo#11]
Hello, I can't make work your  NFT example:
https://yihau.github.io/solana-web3-demo/advanced/metaplex/get-tokenmeta.html

`import { programs } from "@metaplex/js";`
but I get "programs" is not defined in Metaplex/JS, where did you get that from? I am using latest Metaplex. Your code seems to have a reference error.
![image](https://user-images.githubusercontent.com/93995909/148248448-428120c6-4e85-4fbc-9f9d-d87ce1239bf4.png)

**Comment by yihau** [comment]
You can use `ts-node` to run all examples.
Not sure how you run your code and what's your code look like.
I don't think you can embed typescript code in html directly without any translation.
You can try some frontend framework like react or vue. it will pack all code for you and build a page.

**Comment by Ben-v-starloop** [comment]
I use standard Typescript translator that converts Typescript code in JavaScript and simply embed all. https://niutech.github.io/typescript-compile/

Usage demo here: view-source:https://niutech.github.io/typescript-compile/demo/demo.html

I simply placed your code in a seperate .ts file, then with a blank HTML page I try to load it , but this {programs} in lowercase seems to not exists at all, where did you take it from?

**Comment by Ben-v-starloop** [comment]
you do:
`import { Metadata } from "@metaplex-foundation/mpl-token-metadata";
`
but from official MetaPlex Repository (https://github.com/metaplex-foundation/metaplex/)
 I don't find this path:
**" metaplex-foundation/mpl-token-metadata"**

as you see only js folder, no such path, so where did you get that path from ?
![image](https://user-images.githubusercontent.com/93995909/148555859-c96deb5e-f35f-4c05-9ba1-ee96aa7d784c.png)

**Comment by yihau** [comment]
https://github.com/metaplex-foundation/metaplex-program-library
