### ISSUE TITLE
如何批量转账

### ISSUE THREAD

**Issue by lly835** [yihau/solana-web3-demo#13]
一个sol钱包一次转给20个钱包

**Comment by yihau** [comment]
https://yihau.github.io/solana-web3-demo/zh/tour/transfer.html
這個是如何轉帳的程式碼

核心概念在於 `new Transaction().add` 這個可以一次add多個instructions
而一個transfer就是一個instruction

這邊有add多個instruction的參考案例 https://yihau.github.io/solana-web3-demo/zh/tour/create-mint.html

所以你只要add多個transfer的instruction到同一個tx內 就可以實現你想做的事情
