### ISSUE TITLE
关于create token account的疑问

### ISSUE THREAD

**Issue by vae520283995** [yihau/solana-web3-demo#3]
https://github.com/yihau/solana-web3-demo/blob/1352473a9be2140494676b151272b3aa2857e0c4/token/create-token-account/main.ts#L22
这里描述说有两种方式,第二种相当于owner和mint和token account是确定性生成的关系,是现在转账的主流做法
我想问的是第一种方法:
1.如果有钱包随机给你的地址生成一个例如是USDT的token account并且转账了,那么接收方怎么知道这个随机生成的token地址?
2.他还能不能再生成一个新的继续转账,如果可以旧的会消失吗?
3.这个和第二点相同:如果有人既用第一种,也用第二种给我创建token account,这两个account会不会共存?
4.如果有人恶意给别人随机创建token account能实现吗?
@yihau 麻烦指点下,谢谢

**Comment by yihau** [comment]
1. 可以parse當筆tx的資料得知，或是可以用[這裡的範例](https://github.com/yihau/solana-web3-demo/blob/main/token/get-all-account-by-owner/main.ts)撈到你owner所屬得所有token account
2. 可以的，不會消失，會共存
3. 會共存的，這兩個是不同的地址，只是owner都是你而已
4. 可以實現，不過應該不能算是惡意，畢竟創這個地址是需要打錢進去的。有人幫我省下一筆應該算是挺划算的！

**Comment by vae520283995** [comment]
> 1. 可以parse當筆tx的資料得知，或是可以用[這裡的範例](https://github.com/yihau/solana-web3-demo/blob/main/token/get-all-account-by-owner/main.ts)撈到你owner所屬得所有token account
> 
> 2. 可以的，不會消失，會共存
> 
> 3. 會共存的，這兩個是不同的地址，只是owner都是你而已
> 
> 4. 可以實現，不過應該不能算是惡意，畢竟創這個地址是需要打錢進去的。有人幫我省下一筆應該算是挺划算的！

谢谢，明白了，意思就是如果有人通过第二种方式，我就不需要解析create account，因为我可以自己计算出来，如果第一种就需要解析并保存，或者通过api获取这个地址拥有的token account
