### ISSUE TITLE
如何啟動一個 solana-test-validator?

### ISSUE THREAD

**Issue by cl510804194** [yihau/solana-web3-demo#4]
<img width="568" alt="WeChat1535b53481e9f4118e6c8eaee4e18c61" src="https://user-images.githubusercontent.com/42998038/121484936-46b5d880-ca02-11eb-919b-91b4d7ebee9b.png">
我在代碼中看見這個註釋，但是並沒有找到如何啟動它的方法

**Comment by yihau** [comment]
嗨你好！
你如果有裝好solana cli工具的話他就有一起幫你安裝好了

可以參考這裡
https://github.com/yihau/solana-web3-demo/tree/main/prepare#%E9%96%8B%E5%A7%8B

**Comment by yihau** [comment]
有問題隨時都可以再發issue告訴我喔!

**Comment by cl510804194** [comment]
特別感謝，我安裝了solana的cli包後，其他命令可以執行，但是solana-test-validator卻找不到，嘗試了很多方法了，您知道如何解決嗎，我的電腦是windows系統，具體情況如下
![image](https://user-images.githubusercontent.com/42998038/122154245-1d2ffd80-ce97-11eb-8d47-9040139e52e3.png)

**Comment by yihau** [comment]
solana-test-validator會一起安裝在solana的同層目錄下
可以先找到solana安裝的目錄
再去找找裡面有沒有solana-test-validator

**Comment by cl510804194** [comment]
並沒有呢，我安裝的1.6.6版本也是一樣的，很奇怪
![image](https://user-images.githubusercontent.com/42998038/122155568-d1328800-ce99-11eb-9ebf-de00052ade60.png)

**Comment by yihau** [comment]
非常抱歉！
我剛剛看了一下solana discord的討論群
他們有說他們目前不支援Windows的夥伴使用validotors
如果你需要做範例內的東西的話可能要直接使用他們的測試節點了 (https://api.devnet.solana.com)

**Comment by cl510804194** [comment]
好的感谢

**Comment by cl510804194** [comment]
我这里今天使用插件钱包的时候，有两个疑惑，我添加到了todo中，大佬如果知道的话，能否解答一下呢？

**Comment by cl510804194** [comment]
我這裏今天使用插件錢包的時候，有兩個疑惑，我添加到了todo中，大佬如果知道的話，能否解答一下呢？
![image](https://user-images.githubusercontent.com/42998038/122251698-5602bd80-cefd-11eb-9cdf-73417569a8ad.png)

**Comment by yihau** [comment]
抱歉啦
錢包方面我就沒有特別研究了
或許可以去sollet那邊找找看看 💪
