### ISSUE TITLE
Bug report: sendAndConfirmTransaction这一行会报错： TypeError: unexpected type, use Uint8Array

### ISSUE THREAD

**Issue by will-yijinin** [yihau/solana-web3-demo#5]
https://github.com/yihau/solana-web3-demo/blob/main/1.basic/2.account/transfer/main.ts

发送一笔交易时，sendAndConfirmTransaction这一行会报错： TypeError: unexpected type, use Uint8Array。使用的版本是"@solana/web3.js": "^1.10.0"

```
    TypeError: unexpected type, use Uint8Array

      61 |     tx.feePayer = feePayer.publicKey;
      62 |   
    > 63 |     console.log(await sendAndConfirmTransaction(connection, tx, [feePayer]));
```

**Comment by yihau** [comment]
你好
範例的執行目前都是用ts-node來運作
想請問一下你是怎麼執行的呢

**Comment by will-yijinin** [comment]
嗯，用ts-node就可以了，谢谢
