### ISSUE TITLE
关于@solana/spl-token这个库的疑问

### ISSUE THREAD

**Issue by cl510804194** [yihau/solana-web3-demo#6]
我在代码中看到这个库的使用，但是并没有找到关于其api的使用文档，只有npm包的地址，能否发下api文档地址呢 感谢

**Comment by yihau** [comment]
https://github.com/solana-labs/solana-program-library/tree/master/token/js
源碼在這邊
目前我還沒有看到什麼官方支援的文檔
像是web3就有一個滿清楚的文檔
但spl token目前還沒看到
在還沒支援之前
如果你有什麼其他範例需求可以發另外的issue來
